---
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: [3000:3000]
    networks: [app-network]
    depends_on: [backend]
  frontend-tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    depends_on: [frontend]
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: [8000:8000]
    networks: [app-network]
networks:
  app-network:
    driver: bridge
