---
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: som38/final-frontend:${IMAGE_TAG:-latest}
    ports: [3000:3000]
    networks: [app-network]
    depends_on: [backend]
  frontend-tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: som38/final-backend:${IMAGE_TAG:-latest}
    ports: [8000:8000]
    networks: [app-network]
networks:
  app-network:
    driver: bridge
