FROM python:3.11-slim-buster AS builder

WORKDIR /app

COPY requirements.txt ./

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --no-cache-dir -r requirements.txt

COPY manage.py ./

COPY backend backend
COPY api api

FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /app .
COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

EXPOSE 8000

RUN python manage.py migrate 

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
