---
name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: som38
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Store your token in GitHub Secrets
      - name: Run frontend tests
        run: |-
          docker compose build frontend-tests
          docker compose run frontend-tests
      - name: Build and push images with Docker Compose
        env:
          IMAGE_TAG: prod
        run: |-
          docker compose build
          docker compose push
